language: cpp
compiler:
  - gcc
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: ./autogen.sh && ./configure --enable-tests && make test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml++2.6-dev
      - libarchive-dev
      - autoconf
      - automake
      - bison
os:
  - linux
